# Generated by Django 3.1.5 on 2021-01-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibasic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kraska',
            name='jaminarxi',
        ),
    ]
